config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # a comment belongs to a post
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # a post has many comments
  # dependent: :destroy means that when a post gets deleted, any of the its comments also gets deleted
  has_many :comments, dependent: :destroy
	# title of the post must be present and have a minimum length of 5 characters
	validates :title, presence: true, length: {minimum: 5}
	# body of the post must be present
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # this finds the post via :post_id
    @post = Post.find(params[:post_id])
    # defining comment as, .create is activerecord
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    # this leads back to that individual post the user is commenting on
    redirect_to post_path(@post)
  end

  def destroy
    # this finds the post via :post_id
    @post = Post.find(params[:post_id])
    # this finds the comments for the specific post
    @comment = @post.comments.find(params[:id])
    # this deletes the individual comment
    @comment.destroy
    # this redirects to the specific post we deleted comments from
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
		# this will list all the posts with the newer posts on top
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	# in order to save post
	def create
	# this creates/saves the post
	@post = Post.new(post_params)
		# if a post saves, were going to redirect to the post itself to view it
		if @post.save
			redirect_to @post
		else
			# "/post/new" url
			# we want render instead of redirect because 
			# render keeps the content in place whereas 
			# redirect loads another page and content is lost
			render 'new'
		end
	end

	def show
		# define @post
		# find post by post id
		@post = Post.find(params[:id])
	end

	# editing a post
	def edit
		# this finds the post that we want to edit
		@post = Post.find(params[:id])
	end

	# updates the post that we are trying to edit
	def update
		# this finds the post that we want to edit
		@post = Post.find(params[:id])
		# we have the permit for title and body because we included them in the private method below 
		if @post.update(params[:post].permit(:title, :body))
			# this redirects to the show page
			redirect_to @post
		else
			# edit form to show
			render 'edit'
		end
	end
	# method that deletes a post
	def destroy
		# this finds the post that we want to delete
		@post = Post.find(params[:id])
		# deletes the post
		@post.destroy
		# redirects to all the root where list of posts are shown
		redirect_to root_path
	end

	# security feature
	# WARNING this must be at the end of all methods
	# or else any methods below will be private/errors will occur
	private
	# which params we will allow - strong parameters
	# post_params we defined above in Post.new
	def post_params
		# permitting the title and body for the post
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- what the comments will actually look like -->
<!-- how they're going to be structured -->

<!-- each comment is going to be inside a class comment -->
<div class="comment clearfix">
  <!-- comment content div -->
  <!-- we put it in a content_content because we're going to add a delete button -->
  <div class="comment_content">
    <!-- name/body/time of a comment -->
    <p class="comment_name"><strong><%= comment.name %></strong>/<p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <!-- button link to delete a comment and an alert confirming if we want to delete -->
  <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' }%>
  </p>
</div>

app/views/comments/_form.html.erb
<!-- form partial -->
<!-- form for a comment with in the post -->
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <br>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlogCheatsheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- this is the google fonts link that makes the special font possible -->
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>
		<ul>
			<li class="category">Social</li>
			<li><a href="www.facebook.com">Facebook</a></li>
		</ul>

		<!-- this is where the user can login -->
		<p class="sign_in">Admin Login</p>
	</div>

	<div id="main_content">
		<div id="header">
			<!-- if statement using which current page the user is on -->
			<!-- if we are at the home page, show all posts-->
			<% if current_page?(root_path) %>
			<!-- All posts will show (index page)-->
				<p>All Posts</p>
			<!-- if current page is the about page, show the about page -->
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<!-- if looking at a particular post selected from the all posts page, shows clickable link at the top leading back to all posts -->
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>


			<div class="buttons">
				<!-- this button leads to the page where you can make a new post -->
				<button class="button"><%= link_to "New Post", new_post_path %></button>
				<!-- logs the user out -->
				<button class="button">Log Out</button>
			</div>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<!-- yield tag in content div so posts will be next to sidebar instead of behind -->
		<%= yield %>
	</div>


</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <h1>About page that is empty for now</h1>
</div>

app/views/posts/_form.html.erb
  <!-- add form -->
  <!-- form_for method for :post, url for post path so it can submit the post -->
  <!-- then we changed ":post, url: posts_path" to "@post" -->
  <%= form_for @post do |f| %>
    <!-- this will show any errors if there are any -->
    <% if @post.errors.any? %>
      <div id="errors">
        <!-- pluralize will pluralize the word error if there are more than 1...2,3 -->
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
        <ul>
          <!-- this will list all of the error messages if any -->
          <% @post.errors.full_messages.each do |msg| %>
            <!-- each individual message -->
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <!-- post title -->
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>
    <p>
    <!-- post text -->
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    </p>
    <p>
    <!-- submit button -->
    <%= f.submit "publish" %>
    </p>
    
  <% end %>

app/views/posts/edit.html.erb
<!-- this fixes the formatting so that the new form look better-->
<div id="page_wrapper">
  <!-- heading for new posts -->
  <h1>Edit Posts</h1>
  <!-- this will grab the partial for us -->
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<!-- create a loop to go through each of the posts -->
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title">
			<!-- links to a single post. that post title, post path -->
			<%= link_to post.title, post %>
		</h2>
		<p class="body">
			<!-- links to a single post. that post bodym post path -->
			<%= link_to post.body, post %>
		</p>
		<p class="date">
		<!-- this will show mm/dd/yyyy format -->
			<%= post.created_at.strftime("%m, %d, %y") %>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<!-- this fixes the formatting so that the new form look better-->
<div id="page_wrapper">
	<!-- heading for new posts -->
	<h1>New Posts</h1>
	<!-- this will grab the partial for us -->
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<!-- this fixes the formatting so that each individual post looks better-->
<div id="post_content">
	<!-- show title, date/time(when the post was submitted at) and body of the post -->
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		<!-- will show submitted time... and grab post -->
		<!-- the line after the pipe "|" adds the ability for us to edit the post which brings us to the edit form -->
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		| <%= link_to 'Edit', edit_post_path(@post) %>
		| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>
	<!-- will wrap around all the comments -->
	<!-- comment partial -->
	<div id="comments">
		<!-- count number of comments -->
		<h2><%= @post.comments.count %> Comments</h2>
		<!-- grabbing _comments.html.erb -->
		<%= render @post.comments %>
		<h3>Add a comment:</h3>
		<!-- grabbing the _form.html.erb -->
		<%= render "comments/form" %>
	</div>
</div>